src/models/player.ts

modelsディレクトリ配下にplayer.tsを作成しました。

Playermodel作成

---

src/models/stone.ts

Stone model 

---

package-lock.json
src/config.ts

stoneのデータ追加とtableのphase変更を行いました！

 fixed config

---

src/App.vue
src/models/table.ts

App.vueがcreateされるタイミングでtableインスタンスを作成しています。
その時点ではBoardとPlayerはnullであると思われるため、table.tsを修正しています。

App.vue data

---

src/config.ts
src/models/player.ts
src/views/Login.vue

一旦login.vue data作りました。
以下は後ほど実装します。
・名前を入力しない時のメッセージ表示(rulesを利用)
・Game ModeとColorが未選択、名前空欄時には次のページに行かない
・Mode選択時の動的な描画(VS CPUだったらPlayer1しか表示させない)
・色の選択の連動(Player1がwhiteを選択したら、Player2はblackしか選択できない)

first commit login.vue data

---

src/@types/flipAnimation.d.ts

buildの時にいつもエラー出ていたタイプエラーをひとまず解決しました。
そのうちまたflipAninmation.js自体をリファクタリングして、あわよくばtsファイルにします。

feat: flipAnimation.d.ts作成

---

src/components/Stone.vue
src/views/Game.vue

Game.vueからStone.vueにpropsを渡す実装をしました。

feat: Game.vueからStone.vueにpropsを渡す

---

src/models/board.ts
src/modules/boardBuilder.ts

enclosureControllerをboard.tsとboardBuilderに追加したので確認をお願いします！

Refactor board

---

src/config.ts
src/interfaces/config.ts
src/models/board.ts
src/models/player.ts
src/modules/boardBuilder.ts
src/views/Game.vue
src/views/Login.vue

放置してたissue#66の実装しました。
既にtableをpropsしてあったので、そこから値(プレイヤーの名前)を取り出しました。
CPUの名前は'CPU'にしてますが、Configの値を変えれば変更可能です。
プレイヤーの初期スコアもConfigから表示できるようにしてます。

Add props players

---

src/modules/localStorage.ts
src/views/Game.vue

LocalStorageクラスに処理を分けたので、確認をお願いします！

Refactor localstorage

---

src/modules/checkAllowedSquares.ts

ご指摘の箇所の修正を行いました！
インスタンス化はrefactorとしてくろさんのExtension filipをマージしてからやろうと思います。
あと最新版のdevelopのboardBuilder.tsで出ているエラーを修正しているので、マージする時はこちらでマージしていただけますでしょうか？

fix: checkOneDirection

---

src/modules/boardBuilder.ts
src/modules/localStorage.ts

すいません！boardBuilderのエラーが直ってないので確認の上マージいただけますでしょうか？

fix: boardBuilder

---

src/models/allowedDirections.ts
src/models/square.ts
src/modules/boardBuilder.ts
src/modules/checkAllowedSquares.ts
src/views/Game.vue

extensionFilipから別ブランチを切って、allowedDirectionsのインスタンスを作成しましたが、以下の部分がうまく動作しません。。
initialGameからsearchAllowedSquaresを呼び出した時には正しく値が入っているように見えます。
しかしGame.vue上では全てリセットされた値が入ってしまいます。
石の置ける場所のみオブジェクトは作成されてはいます。原因がわからず今日の集まりのときでもよいので少し見ていただけると助かります。。

refactor: create AllowedDirections

---

src/modules/flipAnimation.js
src/views/Game.vue

フリップする時に見えていた下のぶぶ時に見えていた下の部分を見えなくしました！
https://user-images.githubusercontent.com/72016706/143670270-e74d8700-d123-4824-ae01-d4d40a0d568a.mov

Ix flip animation missmatch

---

src/views/Game.vue

square.idを使うようにしました。意外と変更点は少ないです。

refactor: use square.id

---

src/components/PopUp.vue
src/modules/checkAllowedSquares.ts
src/modules/flipAnimation.js
src/views/Game.vue

Popupからゲーム盤面リセットを実装しました！
boardBuilderの実装はよくみたら汎用性がないため、Game.vue上の情報をリセットして実施してます。
Topに遷移するときは名前を初期化してます。

Reset game

---

src/components/PopUp.vue

router.pushを実施しないと同一vue内でも動作しないことがあったので、Retryボタン投下時のredirectGameの処理に追加しました！

fix: add router push in redirectGame

---

src/views/Game.vue

細かい修正ですが、オセロの初期位置は左上と右下が白でした。
そこだけ修正しています。
```
this.table.board.squares[3][3].stone = new Stone(Config.stone.color.white);
this.table.board.squares[4][4].stone = new Stone(Config.stone.color.white);
this.table.board.squares[3][4].stone = new Stone(Config.stone.color.black);
this.table.board.squares[4][3].stone = new Stone(Config.stone.color.black);
```

refactor:石の初期配置変更

---

src/components/PopUp.vue
src/components/SkipDialog.vue
src/views/Game.vue

スキップダイアログを作成しました！
- コンポーネントの作成
- PipUpにvuetifyのdialogタグ追加
- skipダイアログの表示時間が短いと感じたので3秒にして見ました！
https://user-images.githubusercontent.com/72016706/144029201-85372dfe-c263-4610-a010-5e0cd3af094f.mov

feat: create skip dialog

---

src/components/PopUp.vue
src/components/SkipDialog.vue
src/views/Game.vue

PC &スマホ表示の際に画面に収まりきらないので修正しています。
PC表示は90px→65px
スマホ表示は50px⇨40pxに変更しています。

Fix layout

---

src/views/Game.vue
src/views/Login.vue

Game.vueとlogin.vueのフォントを修正しました

refactor: font修正

---

src/views/Game.vue

PATCH: comment in
